# Generated by Django 4.0.4 on 2022-04-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bithdate',
            new_name='birthdate',
        ),
    ]
